name: "Upload BPF"
description: "Uploads an anchor program as a bpf"
inputs:
  program:
    description: 'The program to build and upload'
    required: true
  buffer:
    description: "The buffer address"
    required: true
  keypair:
    description: 'The keypair to use for deploys'
    required: true
  network:
    description: "The solana cluster/network"
    required: true
    default: devnet
  governance:
    description: "The public key of the governance"
    required: true
  signatory:
    description: 'Who must sign off to get this out of draft state?'
    required: true
  name:
    description: 'The name on the proposal'
    required: true
  description:
    description: 'The description on the proposal'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: echo "$DEPLOY_KEYPAIR" > ./deploy-keypair.json && chmod 600 ./deploy-keypair.json
      shell: bash
      env:
        DEPLOY_KEYPAIR: ${{ inputs.keypair }}
    - run: npm install -g @strata-foundation/governance-cli
      shell: bash
    - name: Transfer buffer to governance
      shell: bash
      run: solana program set-buffer-authority $BUFFER -k ./deploy-keypair.json --new-buffer-authority $GOVERNANCE -u $NETWORK
      env:
        BUFFER: ${{ inputs.buffer }}
        GOVERNANCE: ${{ inputs.governance }}
        NETWORK: ${{ inputs.network }}
    - name: Create proposal
      shell: bash
      run: create-proposal
      env:
        PROGRAM_ID: Ep23h6U7HvBb2NRGRTxxH5mekpV4V3b6AJh76mra5Yiv
        BUFFER: ${{ inputs.buffer }}
        GOVERNANCE_KEY: ${{ inputs.governance }}
        NETWORK: ${{ inputs.network }}
        WALLET: ./deploy-keypair
        NAME: ${{ inputs.name }}
        DESCRIPTION: ${{ inputs.description }}
        SIGNATORY: ${{ inputs.signatory }}
    - run: rm ./deploy-keypair.json
      shell: bash
      if: always()
