name: "Deploy via Governance"
description: "Uploads an anchor program as a bpf, then creates a proposal to upgrade to this buffer"
inputs:
  program:
    description: 'The program to build and upload'
    required: true
  buffer:
    description: "The buffer address"
    required: true
  keypair:
    description: 'The keypair to use for deploys'
    required: true
  network:
    description: "The solana cluster/network"
    required: true
    default: devnet
  governance:
    description: "The public key of the governance"
    required: true
  signatory:
    description: 'Who must sign off to get this out of draft state?'
    required: true
  name:
    description: 'The name on the proposal'
    required: true
  description:
    description: 'The description on the proposal'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/upload-bpf/
      id: buffer-deploy
      with:
        network: ${{ inputs.network }}
        program: ${{ inputs.program }}
        keypair: ${{ inputs.keypair }}
    - uses: ./.github/actions/create-proposal/
      id: create-proposal
      with:
        program: ${{ inputs.program }}
        network: ${{ inputs.network }}
        buffer: ${{ inputs.buffer }}
        keypair: ${{ inputs.keypair }}
        governance: ${{ inputs.governance }}
        signatory: ${{ inputs.signatory }}
        name: ${{ inputs.name }}
        description: ${{ inputs.description }}