name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SOLANA_CLI_VERSION: 1.8.5
  NODE_VERSION: 17.0.1

jobs:
  test-contracts:
    name: Deploy BPF
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/upload-bpf/
        with:
          network: devnet
          program: spl_token_bonding
