name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SOLANA_CLI_VERSION: 1.8.5
  NODE_VERSION: 17.0.1

jobs:
  deploy-bpf:
    name: Deploy BPF
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-with-gov-proposal/
        id: deploy
        with:
          program: spl_token_bonding
          network: devnet
          keypair: ${{ secrets.DEPLOY_KEYPAIR }}
          governance: GSGB9BDcb29u8fbigqeFLz1JQ64C4G4H5KRQbzNDJUcJ
          signatory: C6uY3FCNz76k5kDjaYtHyedgzXW8fsJABXg3R7rfc7fA
          name: CI Automated Deployment
          description: Test
